apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ardrgo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sosotechnologies/runners.git
    targetRevision: HEAD
    path: argo-artifacts
    kustomize:
      namePrefix: argo-artifacts-
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true